apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: coetech-ms-node
  annotations:
    github.com/project-slug: coe-tech/coetech-ms-node
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: coe-tech
spec:
  type: service
  lifecycle: development
  owner: user:guest
  system: coe-platform
