# Nome da pipeline.
name: Backstage ms deploy

env:
  PROJETO: "backstage-coe"
  EMAIL: "walber.silva@sysmap.com.br"
  NAMESPACE: "backstage"

# Hooks
# on é obrigatório
on:
  push:
    branches: [ master1 ]
  pull_request:
    branches: [ bar ]

# Os jobs que irão rodar
jobs:
  build_job:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0    
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
        npm init -y
        npm install
#     - uses: actions/upload-artifact@v3.1.1
#       with:
#         path: ${{ github.workspace }}/package.json
#         name: skeleton-tar
#         if-no-files-found: error
#         retention-days: 1
        
  kaniko:
   name: kaniko_push
   runs-on: ubuntu-latest
   needs: [build_job]
   steps:
   - uses: actions/checkout@v2.4.0
#    - uses: actions/download-artifact@v3.0.1
#      with:
#        name: skeleton-tar
#        path: ${{ github.workspace }}/package.json
   - name: create env file
     id: env
     run: |
        echo $TEST_ENV_FILE > .env
     env:
       TEST_ENV_FILE : ${{secrets.ENVIRONMENT_FILE}}    
   - name: Kaniko builder
     uses: aevea/action-kaniko@v0.10.0
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_PASSWORD }}
       image: walber7/node-web-app
       tag: ${{ github.run_number }}
  #         cache: true
  #         cache_registry: walber7/cache
  
